# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text=b'IP or Network mask.', max_length=18)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restricted IP',
                'verbose_name_plural': 'Restricted IPs',
            },
        ),
    ]
